FROM bitnamilegacy/spark:3.5
USER root
RUN pip install --no-cache-dir pandas==3.0.6 scikit-learn==1.9.1 pyarrow==25.0.1 joblib==1.6.0 numpy==2.5.3 psycopg2-binary==2.9.9 redis==5.0.1 clickhouse-driver==0.2.6
USER 1001
