global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['banking_kafka_exporter:9308']

  - job_name: 'fastapi_backend'
    static_configs:
      - targets: ['banking_dashboard_backend:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['banking_postgres:5432']

  - job_name: 'spark'
    static_configs:
      - targets: ['banking_spark_master:8080']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['banking_clickhouse:9363']
